version: "3"

services:
  reactexample:
    container_name: codechallenge
    build:
      context: ./jons-app
      dockerfile: Dockerfile
    volumes:
      - './jons-app:/app'
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
