name: Manifest Generation

on:
  release:
    types: [published]
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
       ref: main
    - name: Write File
      uses: DamianReeves/write-file-action@v1.0
      with:
       path: manifest.md
       contents: |
       
         Release number: ${{github.event.GITHUB_REF}}
         
         Release date: ${{github.event.type}}
         
         Release published by:  ${{ github.actor }}
         
         ---
         
       write-mode: append
    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"
    - run: git add manifest.md
    - run: git commit -m "Manifest updated"
    - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
