name: Manifest Generation

on:
  release:
    types: [published]
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Write File
      uses: DamianReeves/write-file-action@v1.0
      with:
       path: manifest.md
       contents: |
         echo "Hello World!"
       write-mode: append
    - name: Run one line
      run:  echo Hello, world!
